name: Docker Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t test-app:latest .

      - name: List docker images
        run: docker images

      - name: print success message
        run: echo "code build successful"   