name: Conditionals Demo

on:
  #push:
    #brnaches: [main]
  pull_request:

jobs:
  Conditional-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: step that runs only on main branch
        if: github.ref == 'refs/heads/main'   
        run: echo "this runs only on the main branch" 

      - name: continew enven if error happens
        continue-on-error: true
        run: |
         echo: "this step will fail but workflow continews"
         exit 1
           

